name: settings_yaml
version: 7.0.0
homepage: https://github.com/bsutton/settings_yaml
description: Provides a simple means of saving/loading settings from a yaml file without the yaml fuss.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  collection: ^1.15.0
  dcli_core: ^3.0.0
  meta: ^1.3.0
  path: ^1.8.0
  uuid: ^3.0.0
  yaml: ^3.0.0
dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.16.2
