name: settings_yaml
version: 5.0.0-beta.1
homepage: https://github.com/onepub-dev/settings_yaml
description: Provides a simple means of saving/loading settings from a yaml file without the yaml fuss.
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  collection: ^1.15.0
  dcli_core: ^2.0.0-beta.5
  meta: ^1.3.0
  path: ^1.8.0
  uuid: ^3.0.0
  yaml: ^3.0.0
dev_dependencies: 
  lint_hard: ^2.0.0
  test: ^1.16.2
