name: simpleyaml
version: 1.0.3
homepage: https://github.com/bsutton/simpleyaml
description: A simple command-line application.
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies: 
  dshell: ^1.9.12
  meta: ^1.0.0
  yaml: ^2.2.0
dev_dependencies: 
  test: ^1.0.0
  pedantic: ^1.9.0
